// src/constants/captions.ts

export const captions = [
    "🔥 New Menu Alert! 🔥\nExperience the perfect balance of smoky grilled steak, fresh herbs, and a zesty lemon kick. 🍋🥩 Our new menu is designed for true food lovers who crave bold flavors in a cozy, premium dining atmosphere. 🍷✨\n📍 Available now – tag your foodie friends and come try it! #NewMenu #SteakLover #PremiumDining",
    "Indulge in perfection. 🥩✨\nJuicy, tender, and grilled to perfection – our newest menu item is here to elevate your dining experience. A hint of garlic, fresh herbs, and a citrus twist make every bite unforgettable. 🍋🔥\nTag someone who needs to try this! #FoodieHeaven #SteakGoals #NewMenu",
    "New menu, who dis? 🥩🔥\nCrispy sear, juicy center, and that zesty lemon-garlic hit. You know you want it. 🍋💥\nPull up. #NewMenu #SteakDoneRight",
    "👀 Can you smell that? That’s the sound of your next favorite meal sizzling to perfection! 🥩🔥\nGarlic, herbs, and a squeeze of fresh lemon—simple, yet unforgettable. 🍋✨\nDrop a 🔥 in the comments if you’re craving this right now! #FoodieLife #SteakPerfection #NewOnTheMenu",
    "✨ A new flavor experience awaits! ✨\nOur latest menu addition combines the rich, smoky taste of perfectly grilled steak with a refreshing citrus twist and aromatic herbs. 🍽️ Whether you're here for a casual night out or a premium dining experience, this one’s for you! 🍷\nCome taste the difference. Reservations recommended! #NewMenu #SteakLover #DiningExperience"
  ];


export const promotion_captions = [
  "🌟 Crispy, golden, and one-of-a-kind! 🌟\nMeet our signature Bloomin’ Onion – a crispy, hand-battered masterpiece you won’t find anywhere else! 🍽️✨\nPerfectly seasoned, deep-fried to golden perfection, and served with our house-made dipping sauce. 🤤🔥\n\nTag your foodie friends and be the first to try this must-have dish! 🍽️🍷\n📍 Available exclusively at The Great Steakhouse.\n\n#SignatureDish #BloominOnion #CrispyGoodness #FoodieHeaven",
  "🚨 Not all restaurants have it… but we do! 🚨\nOur famous Bloomin’ Onion is the ultimate crispy indulgence. 🔥 Crunchy on the outside, tender on the inside, and served with a creamy, tangy dip that keeps you coming back for more. 🍽️🤤\n\n👀 Ready to take a bite? Only available at The Great Steakhouse!\n📍 Tag a friend who needs to try this!\n\n#OnlyHere #BloominOnion #CrispyPerfection #FoodieFind",
  "🍝✨ The Perfect Pairing – Seafood Pasta & White Wine! ✨🍷\nSilky, rich, and packed with ocean-fresh flavors, our Seafood Pasta just found its soulmate – a glass of crisp white wine. 😍\n\nFor a limited time, enjoy 15% OFF on this iconic pairing! 🍽️🍷\n📍 Only available this February – Tag your wine & pasta lover friends!\n\n#PerfectPair #SeafoodPasta #WineLover #FoodieFind #PastaAndWine",
  "🚨 Seafood Lovers, This One’s for You! 🚨\nDid you know that 40% of our guests who order our creamy Seafood Pasta also enjoy it with a refreshing glass of white wine? 🍝🍷\n\nTo celebrate this perfect pairing, we’re offering 15% OFF when you order them together! 🎉\n📅 Limited Time Offer: February 1 - 28\n📍 Dine in today or tag your foodie crew!\n\n#SeafoodPasta #WinePairing #LimitedOffer #FoodieHeaven",
  "🍝 + 🍷 = THE perfect match!\nEnjoy 15% OFF on our creamy Seafood Pasta & crisp White Wine combo this February! 🎉\n\nLimited time only – don’t miss out! ⏳\n📍 Available now at The Great Steakhouse\n\n#PerfectPair #FoodieFind #PastaAndWine #LimitedOffer",
]